In [4]:
A = [2, 4, 6]

a = [int(x) for x in '{0:0b}'.format(6)][::-1]


len('{0:0b}'.format(16))

5

In [222]:
18 % 1

0

In [156]:
A = [[0,2,0], [4,5,6]]

A[0][A[0]==0] = 3

A

[[3, 2, 0], [4, 5, 6]]

In [8]:
import numpy as np 

array([0.01, 0.  , 0.  , 0.99])

In [130]:
def softmax(inp, tau = 1):
    out = np.exp(inp/tau)
    out = out / np.sum(out, axis=1).reshape(-1,1)
    return out

inp = np.array([ [3,1,5], [5,6,6], [7,5,6]])
np.round(softmax(inp), decimals=2)

array([[0.12, 0.02, 0.87],
       [0.16, 0.42, 0.42],
       [0.67, 0.09, 0.24]])

In [131]:
out = softmax(inp)
out_cdf = np.cumsum(out, axis=1)
print(out)
np.sum((out_cdf <= .5).astype(np.int), axis=1)

[[0.11731043 0.01587624 0.86681333]
 [0.1553624  0.4223188  0.4223188 ]
 [0.66524096 0.09003057 0.24472847]]


array([2, 1, 0])

In [65]:
def cdf2pmf(cdf):
    diff_arr = np.eye(len(cdf))
    for k in range(len(cdf)-1):
        diff_arr[k+1, k] = -1
        
    print(np.matmul(cdf, diff_arr))
    return np.matmul(cdf, diff_arr)

cdf = np.array([1., .9, .93, .96, .9, .99])
np.round(softmax(cdf2pmf(cdf), tau = 0.2), decimals=2)

[ 0.1  -0.03 -0.03  0.06 -0.09  0.99]


array([0.01, 0.01, 0.01, 0.01, 0.  , 0.96])